apiVersion: v1
kind: Service
metadata:
  name: openswap-frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000 # Assuming your frontend application runs on port 3000
  type: LoadBalancer # Expose the service outside the cluster
